filme/urls.py
from django.urls import path

from . import views

app_name = 'filmes'

urlpatterns = [
    path('', views.FilmeIndex.as_view(), name='index'),
    path('ord_data_antigo/', views.FilmeIndexDataAntigo.as_view(), name='index_data_antigo'),
    path('ord_data_novo/', views.FilmeIndexDataNovo.as_view(), name='index_data_novo'),
    path('sobre/', views.sobreView, name='sobre'),
    path('projetos/', views.projetosView, name='projetos'),
    path('<int:movie_id>/', views.detailPage, name='detail'),
    path('categoria/<str:categoria>', views.FilmeCategoria.as_view(), name='categoria'),
    path('busca/', views.FilmeBusca.as_view(), name='busca'),
]

perfil/urls.py
from django.urls import path

from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('register/', views.registerPage, name='register'),
]

projebfilmes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls')),
    path('login/', include('perfil.urls')),
    path('comentario/', include('comentario.urls')),
]

# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

perfil/models.py
from django.db import models

# Create your models here.

perfil/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

perfil/views.py
from categoria.models import Categoria
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render

from .forms import RegistrationForm


def loginPage(request):
    if request.user.is_authenticated:
        messages.add_message(
            request,
            messages.WARNING,
            'Você já se encontra logado.'
        )
        return redirect('filmes:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            
            user = authenticate(username=username, password=password)
            
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.add_message(
                        request,
                        messages.SUCCESS,
                        f"Bem vindo(a) {username}, você agora está logado e pode dar nota(s) e escrever comentário(s)."
                    )
                    return redirect('filmes:index')
                else: 
                    return render(request, 'perfil/login.html', {"error": "Sua conta está desabilitada."})
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Ooops... Usuário ou senha estão inválidos.'             
                )
                return render(request, 'perfil/login.html') 
        else:
            categorias = Categoria.objects.order_by('nome_cat')
            context = {'categorias': categorias}
            return render(request, 'perfil/login.html', context)
        

def logoutPage(request):
    if request.user.is_authenticated:
        logout(request)
        messages.add_message(
            request,
            messages.WARNING,
            f'Usuário foi deslogado com sucesso.'
        )
        return redirect('filmes:index')
    else:
        messages.add_message(
            request,
            messages.WARNING,
            f'Você já está deslogado.'
        )
        return redirect('filmes:index')


def registerPage(request):
    if request.user.is_authenticated:
        messages.add_message(
            request,
            messages.WARNING,
            f'Você já se encontra logado.'
        )
        return redirect('filmes:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            form = RegistrationForm(request.POST or None)
            
            if form.is_valid():
                user = form.save()
                
                raw_password = form.cleaned_data.get('password1')
                
                user = authenticate(username=user.username, password=raw_password)
                
                if user is not None:
                    login(request, user)
                    messages.add_message(
                        request,
                        messages.SUCCESS,
                        f"Bem vindo(a) {username}, você agora está cadastrado(a) e pode dar nota(s) e escrever comentário(s)."
                    )
                    return redirect('filmes:index')
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Ooops... você digitou algum campo inválido.'
                )
        else:
            form = RegistrationForm()
        
        categorias = Categoria.objects.order_by('nome_cat')    
        context = {
            'form': form,
            'categorias': categorias
        }
        return render(request, 'perfil/register.html', context)

perfil/templates/perfil/login.html
{% extends 'base.html' %}

{% block titulo %}Login |{% endblock %}

{% block content %}
<br>
{% include 'parciais/_messages.html' %}
<div class="card">
    <div class="card-body">
        <h2 class="text-center">Login</h2>
        <form action="" method="POST">

            {% csrf_token %}
            <label for="username">Usuário</label>
            <input type="text" placeholder="Digite seu nome de usuário" class="form-control" name="username">

            <label for="password">Senha</label>
            <input type="password" placeholder="Digite sua senha" class="form-control" name="password">
            <br>

            {% if error%}
            <i style="color: red">{{ error }}</i>
            {% endif %}

            <br>
            <input type="submit" value="Login" class="btn btn-danger">

        </form>
        <h5 class="text-center">Ainda não é cadastrado? Clique abaixo.</h5>
        <p class="text-center"><a href="{% url 'perfil:register' %}">Criar um novo usuário</a></p>

    </div>
    <div style="margin-bottom: 20px; margin-left: 10px;">
        <a class="btn btn-secondary btnVoltarEnquetes" href="{% url 'filmes:index' %}">Voltar</a>
    </div>
</div>
<br>
{% endblock %}

perfil/templates/perfil/register.html
{% extends 'base.html' %}

{% block titulo %}Registro |{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<br>

{% include 'parciais/_messages.html' %}
<div class="card">
    <div class="card-body">
        <h3 class="text-center">
            Login
        </h3>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Registrar" class="btn btn-danger">
        </form>
    </div>
</div>

<br>
{% endblock %}