comentario/urls.py
from django.urls import path

from . import views

app_name = 'comentario'

urlpatterns = [
    path('addComentario/<int:movie_id>/', views.addComentario, name='addComentario'),
    path('editComentario/<int:movie_id>/<int:comentario_id>', views.editComentario, name='editComentario'),
    path('deleteComentario/<int:movie_id>/<int:comentario_id>', views.deleteComentario, name='deleteComentario'),
    
]

filme/urls.py
from django.urls import path

from . import views

app_name = 'filmes'

urlpatterns = [
    path('', views.FilmeIndex.as_view(), name='index'),
    path('ord_data_antigo/', views.FilmeIndexDataAntigo.as_view(), name='index_data_antigo'),
    path('ord_data_novo/', views.FilmeIndexDataNovo.as_view(), name='index_data_novo'),
    path('sobre/', views.sobreView, name='sobre'),
    path('projetos/', views.projetosView, name='projetos'),
    path('<int:movie_id>/', views.detailPage, name='detail'),
    path('categoria/<str:categoria>', views.FilmeCategoria.as_view(), name='categoria'),
    path('busca/', views.FilmeBusca.as_view(), name='busca'),
]

projebfilmes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls')),
    path('login/', include('perfil.urls')),
    path('comentario/', include('comentario.urls')),
]

# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

comentario/models.py
from django.contrib.auth.models import User
from django.db import models
from filme.models import Filme


class Comentario(models.Model):
    filme = models.ForeignKey(Filme, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuário')
    comentario = models.TextField(max_length=1000, verbose_name='Comentário')
    nota = models.FloatField(default=0)
    
    def __str__(self):
        return self.user.username

filme/models.py
from categoria.models import Categoria
from django.db import models
from django.utils import timezone


class Filme(models.Model):
    nome = models.CharField(max_length=50)
    diretor = models.CharField(max_length=100)
    elenco = models.CharField(max_length=200)
    sinopse = models.TextField(max_length=800)
    data_estreia = models.DateField(default=timezone.now, verbose_name='Data lançamento')
    nota_media = models.FloatField(default=0, verbose_name='Nota Média')
    categoria_filme = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING,  blank=True, null=True, verbose_name='Categoria') 
    imagem_filme = models.URLField(default=None, null=True)
    
    def __str__(self):
        return self.nome
    
    def __unicode__(self):
        return self.nome

filme/forms.py
from django import forms
from django.core.mail import EmailMessage


class ContatoForm(forms.Form):
    nome = forms.CharField(label="Nome", max_length=100)
    email = forms.EmailField(label="E-mail", max_length=100)
    assunto = forms.CharField(label="Assunto", max_length=100)
    mensagem = forms.CharField(label="Mensagem", widget=forms.Textarea())

    def send_email(self):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        assunto = self.cleaned_data['assunto']
        mensagem = self.cleaned_data['mensagem']

        corpo = f'Nome:{nome}\nMensagem:{mensagem}'

        mail = EmailMessage(
            subject=assunto,
            from_email='eduardo.ads1814@gmail.com',
            to=[email,],
            body=corpo,
            headers={
                'Replay-To':'eduardo.ads1814@gmail.com'
            }
        )
        mail.send()

filme/views.py
from comentario.models import Comentario
from django.contrib import messages
from django.db.models import Avg, Q
from django.http import Http404
from django.shortcuts import render
from django.views.generic.list import ListView

from .forms import *
from .models import *


class FilmeIndex(ListView):
    model = Filme
    template_name = 'filme/indexNome.html'
    context_object_name = 'allMovies'
    paginate_by = 8
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorias'] = Categoria.objects.all()
        context['categoria'] = self.kwargs.get('categoria', None)
        context['termo'] = self.request.GET.get('termo')
        return context
    
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by('nome')
        return qs

class FilmeIndexDataAntigo(FilmeIndex):
    template_name = 'filme/indexDataAntigo.html'
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by('data_estreia')
        return qs

class FilmeIndexDataNovo(FilmeIndex):
    template_name = 'filme/indexDataNovo.html'
    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by('-data_estreia')
        return qs


class FilmeCategoria(FilmeIndex):
    template_name = 'filme/filme_categoria.html'
    
    def get_queryset(self):
        qs = super().get_queryset()
        
        categoria = self.kwargs.get('categoria', None)
        
        if not categoria:
            return qs
        
        qs = qs.filter(categoria_filme__nome_cat__iexact=categoria)
        
        return qs


class FilmeBusca(FilmeIndex):
    template_name = 'filme/filme_busca.html'
    
    def get_queryset(self):
        qs = super().get_queryset()
        termo = self.request.GET.get('termo')
        
        if not termo:
            return qs
        
        qs = qs.filter(
            Q(nome__icontains=termo) |
            Q(diretor__icontains=termo) |
            Q(elenco__icontains=termo)
        )
        
        return qs
    

def detailPage(request, movie_id):
    try:
        movie = Filme.objects.get(pk=movie_id)
    except:
        return render(request, 'filme/erro.html')
    
    categorias = Categoria.objects.order_by('nome_cat')
    comentarios = Comentario.objects.filter(filme=movie_id)
    
    qtd_votos = len(comentarios)
    
    media = comentarios.aggregate(Avg('nota'))['nota__avg']
    # print(media)
    
    if media == None:
        media = 0
    
    media = round(media, 2)
        
    context = {
        'movie': movie,
        'categorias': categorias,
        'comentarios': comentarios,
        'media': media,
        'qtd_votos': qtd_votos
    }
    return render(request, 'filme/filme_detalhes.html', context)


def sobreView(request):
    if str(request.method) == 'POST':
        form = ContatoForm(request.POST)
        if form.is_valid():
            #chamando método de envio de email
            form.send_email()
            messages.success(request, 'Email enviado com sucesso.')
            form = ContatoForm()
        else:
            messages.error(request, 'Email NÃO FOI enviado com sucesso.')
    else:
        form = ContatoForm()

    categorias = Categoria.objects.order_by('nome_cat')
    context = {
        'form': form,
        'categorias': categorias
    }
    return render(request, 'filme/sobre.html', context)


def projetosView(request):
    categorias = Categoria.objects.order_by('nome_cat')
    
    context = {
        'categorias': categorias
    }
    return render(request, 'filme/projetos.html', context)

filme/templates/filme/detail.html
{% extends 'base.html' %}

{% block content %}

<br>
<img src="{{ movie.imagem_filme }}">
<br>
<h1>{{ movie.nome }}</h1>
<br>
<h4>{{ movie.sinopse }}</h4>
<br>
<h4>Diretor: {{ movie.diretor }}</h4>

<br>
<h4>Elenco: {{ movie.elenco }}</h4>

<br>
<h4>Categoria: {{ movie.categoria_filme }}</h4>

<br>
{% endblock %}

filme/templates/filme/erro.html
{% extends 'base.html' %}

{% block content %}
<br><br><br>

<h2 class="text-center" style="color: white;">Ooooops... filme não encontrado!</h2>

<br><br>
<div class="text-center" style="margin-bottom: 20px;">
    <a class="btn btn-secondary btn-lg btnVoltarSobre" href="/">Início</a>
</div>

<br><br><br>
{% endblock %}

filme/templates/filme/filme_busca.html
{% extends 'filme/index.html' %}

{% block titulo %}{{ termo|title }} | Busca |{% endblock %}

{% block order %}
<p class="text-center">Buscando por: <strong><i>"{{ termo }}"</i></strong></p>
{% endblock %}
{% block botaoVoltar %}
<br>
<div class="text-center" style="margin-bottom: 20px;">
    <a class="btn btn-secondary btnVoltarSobre" href="/">Início</a>
</div>
<br>
{% endblock %}
<!-- adicionar botão de voltar -->

filme/templates/filme/filme_categoria.html
{% extends 'filme/index.html' %}

{% block titulo %}{{ categoria|title }} | Categoria |{% endblock %}

{% block order %}
<p class="text-center" style="margin-top: 0px;">Categoria: <strong><i>{{ categoria }}</i></strong></p>
{% endblock %}
{% block botaoVoltar %}
<br>
<div class="text-center" style="margin-bottom: 20px;">
    <a class="btn btn-secondary btnVoltarSobre" href="/">Início</a>
</div>
<br>
{% endblock %}
<!-- adicionar botão de voltar -->

filme/templates/filme/filme_detalhes.html
{% extends 'base.html' %}

{% block titulo %}{{ movie.nome }} | Detalhes |{% endblock %}

{% block content %}

<br>
{% include 'parciais/_messages.html' %}

<div class="card">
    <div class="row">
        <div class="col-md-4 text-center" style="padding: 10px;">
            <img src="{{ movie.imagem_filme }}" alt="{{ movie.nome }}" class="img-fluid">
        </div>
        <div class="col-md-8">
            <br>
            <h3 class="text-center">{{ movie.nome }}</h3>
            <div style="padding: 10px;">
                <p>{{ movie.sinopse }}</p>
                <p class="text-center" style="font-size: 15px;">
                    <a class="dropdown-item" href="{% url 'filmes:categoria' movie.categoria_filme %}" name="buscar"
                        style="color: #909093; text-decoration: underline;">
                        {{ movie.categoria_filme }}
                    </a>
                </p>
                <h5>Diretor: <span style="font-size: 15px;">{{ movie.diretor }}</span></h5>
                <h5>Elenco: <span style="font-size: 15px;">{{ movie.elenco }}</span></h5>
                {% if media > 5 %}
                <h5>Nota: <span style="color: #0000CD;">{{ media }}</span> / 10</h5>
                {% else %}
                <h5>Nota: <span style="color: #8B0000;">{{ media }}</span> / 10</h5>
                {% endif %}
                <small>Total votos: {{ qtd_votos }}</small>

            </div>
        </div>
    </div>
</div>
<br>

<div class="card">
    <div class="card-body">
        <h3 class="text-center">Deixe aqui seu comentário e nota...</h3>
        <form action="{% url 'comentario:addComentario' movie.id  %}" method="POST">
            {% csrf_token %}
            <label for="comentario">Comentário</label>
            <textarea name="comentario" id="comentario" cols="30" rows="5" class="form-control"></textarea>

            <label for="nota" style="margin-top: 15px; margin-bottom: 15px;">Nota</label>
            <input type="range" id="rangeInput" name="nota" min="0" max="10" value="0" step="0.5"
                oninput="amount.value=rangeInput.value">
            <output name="amount" id="amount" for="rangeInput">0</output>

            <br>
            <input type="submit" class="btn btn-danger" value="Enviar">
        </form>
    </div>
</div>
<br>
<div class="card">
    <div class="card-body">

        <h3 class="text-center" style="margin-bottom: 24px; text-decoration: underline;">Comentários</h3>
        {% for comentario in comentarios %}

        <div class="card" style="background-color: #f5eeee;">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3">
                        <h5 class="text-left">{{ comentario.user.username }}</h5>
                        <h5 class="">{{ comentario.nota }}</h5>

                        {% if request.user == comentario.user %}
                        <a href="{% url 'comentario:editComentario' movie.id comentario.id %}">
                            Edit
                        </a>
                        <a href="{% url 'comentario:deleteComentario' movie.id comentario.id %}"
                            onclick="return confirm('Tem certeza que deseja excluir este comentário ?')">
                            Delete
                        </a>
                        {% endif %}
                    </div>
                    <div class="col-md-9">
                        <p>{{ comentario.comentario }}</p>
                    </div>
                </div>
            </div>
        </div>
        <br>

        {% endfor %}
        <div class="text-center" style="margin-bottom: 20px;">
            <a class="btn btn-secondary btn-lg btnVoltarSobre" href="/">Voltar</a>
        </div>

    </div>
</div>
<br>

{% endblock %}

filme/templates/filme/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block titulo %}Home |{% endblock %}

{% block content %}
<br>

{% if allMovies %}
{% include 'parciais/_messages.html' %}

<div class="row">
    <div class="col-md-12">
        <form class="form-class" action="{% url 'filmes:busca' %}">
            {% csrf_token %}
            <input type="search" name="termo" id="termo" value="{{ request.GET.termo }}" class="form-control"
                placeholder="Nome, diretor, atores..."
                style="margin-top: 22px; margin-bottom: 18px; background-color: #F5F5F5;" />

            <div class="text-center">
                <button type="submit" class="btn btn-light"><strong><i>Buscar</i></strong></button>
            </div>
        </form>

    </div>
</div>
<br>




<div class="card cardCorpo">

    <div class="card-body">
        {% block order %}{% endblock %}
        <div class="row">
            {% for movie in allMovies %}
            <div class="col-md-3">
                <div class="card" style="margin-top: 7px;">
                    <div class="card-body">
                        <div class="text-center">
                            <a href="{% url 'filmes:detail' movie.id %}">
                                <img class="card-img-top" src="{{ movie.imagem_filme }}" alt="{{ movie.name }}">
                            </a>

                            <h6 class="card-title" style="padding-top: 15px;">
                                <a href="{% url 'filmes:detail' movie.id %}" style="color: black;">
                                    {{ movie.nome }}
                                </a>
                            </h6>

                            <p class="card-text">
                                <small class="text-muted">
                                    {{ movie.categoria_filme }} | {{ movie.comentario_set.count }} voto(s)
                                    <br>
                                    {{ movie.data_estreia|naturalday|title }}
                                </small>
                            </p>
                        </div>
                        <div class="text-right" style="padding-top: 10px;">
                            <a href="{% url 'filmes:detail' movie.id %}" style="color: #4F4F4F;">
                                <strong><i>Leia mais...</i></strong>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% else %}
            <br>
            <p class="text-center" style="color: white;"><strong>Nenhum filme foi encontrado...</strong></p>

            {% endif %}
        </div>

        <br>
        {% include 'parciais/_pagination.html' %}
        {% block botaoVoltar %}{% endblock %}

    </div>
</div>

<br>
{% endblock %}

filme/templates/filme/indexDataAntigo.html
{% extends 'filme/index.html' %}
{% block order %}
<p class="text-center" style="margin-top: 0px;">Ordenado por <strong><i>data (antigo)</i></strong>.</p>
{% endblock %}

filme/templates/filme/indexDataNovo.html
{% extends 'filme/index.html' %}
{% block order %}
<p class="text-center" style="margin-top: 0px;">Ordenado por <strong><i>data (novo)</i></strong>.</p>
{% endblock %}

filme/templates/filme/indexNome.html
{% extends 'filme/index.html' %}
{% block order %}
<p class="text-center" style="margin-top: 0px;">Ordenado por <strong><i>nome</i></strong>.</p>
{% endblock %}

filme/templates/filme/projetos.html
{% extends 'base.html' %}

{% block titulo %}Outros Projetos |{% endblock %}

{% block content %}

<br>
<div class="card-group">
    <div class="card">
        <a href="http://quiz-django-edu.herokuapp.com"><img class="card-img-top"
                src="https://raw.githubusercontent.com/EduardoBran/Quiz-Web-Application-Py/main/screenshot/screenshot.jpg"
                alt="Imagem do projeto QuizTime"></a>
        <div class="card-body">
            <h5 class="card-title text-center">Projeto QuizTime</h5>
            <p class="card-text">Este é um projeto de um quiz interativo sobre tecnologia.</p>
        </div>
        <div class="card-footer text-center">
            <small class="text-muted">
                <a href="http://quiz-django-edu.herokuapp.com">
                    Clique aqui para acessar
                </a>
            </small>
        </div>
    </div>
    <div class="card">
        <a href="https://sistema-enquetes.herokuapp.com/"><img class="card-img-top"
                src="https://raw.githubusercontent.com/EduardoBran/System-Voting-App-Web-Py/main/screenshot/screenshot2.jpg"
                alt="Imagem do projeto PollMaker"></a>
        <div class="card-body">
            <h5 class="card-title text-center">Projeto PollMaker</h5>
            <p class="card-text">Este é um projeto de sistema de enquetes.</p>
        </div>
        <div class="card-footer text-center">
            <small class="text-muted">
                <a href="https://sistema-enquetes.herokuapp.com/">
                    Clique aqui para acessar
                </a>
            </small>
        </div>
    </div>
    <div class="card">
        <a href="https://blog.eduardomb.com.br"><img class="card-img-top"
                src="https://raw.githubusercontent.com/EduardoBran/Projeto-Blog-Web-Py/main/screenshot/screenshot.jpg"
                alt="Imagem do projeto Blog do EduAds"></a>
        <div class="card-body">
            <h5 class="card-title text-center">Projeto Blog</h5>
            <p class="card-text">Este é um projeto de um blog sobre tecnologia.</p>
        </div>
        <div class="card-footer text-center">
            <small class="text-muted">
                <a href="https://blog.eduardomb.com.br">
                    Clique aqui para acessar
                </a>
            </small>
        </div>
    </div>
    <div class="card">
        <a href="https://appweatherdjango.herokuapp.com"><img class="card-img-top"
                src="https://raw.githubusercontent.com/EduardoBran/Weather-App-Web/main/screenshot/screenshot.jpg"
                alt="Imagem do projeto Blog do EduAds"></a>
        <div class="card-body">
            <h5 class="card-title text-center">Projeto AppWeather</h5>
            <p class="card-text">Este é um projeto para consultar o clima através de uma api.</p>
        </div>
        <div class="card-footer text-center">
            <small class="text-muted">
                <a href="https://appweatherdjango.herokuapp.com">
                    Clique aqui para acessar
                </a>
            </small>
        </div>
    </div>
</div>
<br>
<div class="text-center" style="margin-bottom: 20px;">
    <a class="btn btn-secondary btnVoltarSobre" href="/">Voltar</a>
</div>
<br><br>

{% endblock %}

filme/templates/filme/sobre.html
{% extends 'base.html' %}

{% block titulo %}Sobre |{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% include 'parciais/_messages.html' %}

<div class="card cardSobre shadow border sobre">
    <div class="card-body d-flex flex-column">
        <h4 class="card-title text-center" style="padding-bottom: 10px;">Sobre</h4>
        <p class="card-text text-center">Esta aplicação foi feita utilizando as tecnologias:</p>
        <ul class="" style="background-color: white ;">
            <li>Python</li>
            <li>Django</li>
            <li>Html</li>
            <li>Css</li>
            <li>Bootstrap</li>
            <li>Banco de Dados</li>
        </ul>
        <p class="card-text text-center">
            Você pode me enviar um e-mail com críticas e/ou sugestões através do formulário abaixo.
        </p>
    </div>
    <br>
    <h3 class="text-center">Enviar e-mail</h3>
    <br>
    <form action="{% url 'filmes:sobre' %}" method="POST" class="form">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-dark">Enviar</button>
    </form>
    <br>
    <strong>
        <p class="card-text text-center">Desenvolvido por Eduardo Brandão</p>
        <p class="card-text text-center">Versão 1.0</p>
    </strong>
    <br>
    <div class="text-center" style="margin-bottom: 20px;">
        <a class="btn btn-secondary btnVoltarSobre" href="/">Voltar</a>
    </div>
</div>
<br><br>

{% endblock %}