filme/urls.py
from django.urls import path

from . import views

app_name = 'filmes'

urlpatterns = [
    path('', views.FilmeIndex.as_view(), name='index'),
    path('ord_data_antigo/', views.FilmeIndexDataAntigo.as_view(), name='index_data_antigo'),
    path('ord_data_novo/', views.FilmeIndexDataNovo.as_view(), name='index_data_novo'),
    path('sobre/', views.sobreView, name='sobre'),
    path('projetos/', views.projetosView, name='projetos'),
    path('<int:movie_id>/', views.detailPage, name='detail'),
    path('categoria/<str:categoria>', views.FilmeCategoria.as_view(), name='categoria'),
    path('busca/', views.FilmeBusca.as_view(), name='busca'),
]

perfil/urls.py
from django.urls import path

from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('register/', views.registerPage, name='register'),
]

projebfilmes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls')),
    path('login/', include('perfil.urls')),
    path('comentario/', include('comentario.urls')),
]

# urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/parciais/_footer.html
{% load static %}


<style>
    .site-footer {
        background-color: #343a40;
        padding: 45px 0 20px;
        font-size: 15px;
        line-height: 24px;
        color: #737373;
    }

    .site-footer hr {
        border-top-color: #bbb;
        opacity: 0.5
    }

    .site-footer hr.small {
        margin: 20px 0
    }

    .site-footer h6 {
        color: #fff;
        font-size: 16px;
        text-transform: uppercase;
        margin-top: 5px;
        letter-spacing: 2px
    }

    .site-footer a {
        color: #737373;
    }

    .site-footer a:hover {
        color: #3366cc;
        text-decoration: none;
    }

    .footer-links {
        padding-left: 0;
        list-style: none
    }

    .footer-links li {
        display: block
    }

    .footer-links a {
        color: #737373
    }

    .footer-links a:active,
    .footer-links a:focus,
    .footer-links a:hover {
        color: #3366cc;
        text-decoration: none;
    }

    .footer-links.inline li {
        display: inline-block
    }

    .site-footer .social-icons {
        text-align: right
    }

    .site-footer .social-icons a {
        width: 25px;
        height: 20px;
        line-height: 40px;
        margin-left: 6px;
        margin-right: 0;
        border-radius: 100%;
        background-color: #33353d;
    }

    .copyright-text {
        margin: 0
    }

    @media (max-width:991px) {
        .site-footer [class^=col-] {
            margin-bottom: 30px
        }
    }

    @media (max-width:767px) {
        .site-footer {
            padding-bottom: 0
        }

        .site-footer .copyright-text,
        .site-footer .social-icons {
            text-align: center
        }
    }

    .social-icons {
        padding-left: 0;
        margin-bottom: 0;
        list-style: none
    }

    .social-icons li {
        display: inline-block;
        margin-bottom: 4px
    }

    .social-icons li.title {
        margin-right: 15px;
        text-transform: uppercase;
        color: #96a2b2;
        font-weight: 700;
        font-size: 13px
    }

    .social-icons a {
        background-color: #eceeef;
        color: #818a91;
        font-size: 16px;
        display: inline-block;
        line-height: 44px;
        width: 44px;
        height: 44px;
        text-align: center;
        margin-right: 8px;
        border-radius: 100%;
        -webkit-transition: all .2s linear;
        -o-transition: all .2s linear;
        transition: all .2s linear;


    }

    .social-icons a:active,
    .social-icons a:focus,
    .social-icons a:hover {
        color: #fff;
        background-color: #29aafe
    }

    .social-icons.size-sm a {
        line-height: 34px;
        height: 34px;
        width: 34px;
        font-size: 14px
    }

    .social-icons a.facebook:hover {
        background-color: #3b5998
    }

    .social-icons a.twitter:hover {
        background-color: #00aced
    }

    .social-icons a.linkedin:hover {
        background-color: #007bb6
    }

    .social-icons a.dribbble:hover {
        background-color: #ea4c89
    }

    @media (max-width:767px) {
        .social-icons li.title {
            display: block;
            margin-right: 0;
            font-weight: 600
        }
    }
</style>

<!-- Site footer -->
<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>Sobre</h6>
                <p class="text-justify" style="color: #DCDCDC;">
                    A aplicação web EbFilmes foi criada com o propósito de que o usuário consiga
                    compartilhar sua opinião com comentário e nota a respeito dos filmes escolhidos. Para o
                    desenvolvimento deste sistema foi utilizado Python, o web framework Django e Bootstrap e CSS no seu
                    layout.
                </p>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Categorias</h6>
                <ul class="footer-links">
                    {% for categoria in categorias %}
                    <li>
                        <a class="dropdown-item" href="{% url 'filmes:categoria' categoria.nome_cat %}" name="buscar"
                            style="color: #909093;">
                            {{ categoria.nome_cat }}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Quick Links</h6>
                <ul class="footer-links">
                    <li>
                        <a href="{% url 'filmes:sobre' %}" style="color: #909093;">Sobre</a>
                    </li>
                    <li>
                        <a href="{% url 'filmes:projetos' %}" style="color: #909093;">Outros Projetos</a>
                    </li>
                    <li>
                        <a href="https://github.com/EduardoBran?tab=repositories" style="color: #909093;">Github</a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/eduardombrandao/" style="color: #909093;">Linkedin</a>
                    </li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text" style="color: #909093;">
                    Desenvolvido por
                    <a href="https://www.linkedin.com/in/eduardombrandao/" style="color: #909093;">
                        Eduardo Brandão
                    </a>
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li>
                        <a class="github" href="https://github.com/EduardoBran?tab=repositories">
                            <i class="fa fa-github"></i>
                        </a>
                    </li>
                    <li>
                        <a class="linkedin" href="https://www.linkedin.com/in/eduardombrandao/">
                            <i class="fa fa-linkedin"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
    crossorigin="anonymous"></script>

<script src="https://kit.fontawesome.com/979f4dc9a1.js" crossorigin="anonymous"></script>

templates/parciais/_head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css'%}">

templates/parciais/_messages.html
{% if messages %}
<br>
{% for message in messages %}
<div class="alert {{ message.tags }}" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <a class="navbar-brand" href="{% url 'filmes:index' %}">EbFilmes</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav" style="padding-left: 10px;">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'filmes:projetos' %}">
                    Outros Projetos
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link active" href="{% url 'filmes:sobre' %}">
                    Sobre
                </a>
            </li>
            <li class="nav-item dropdown">

                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Ordernar por...
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'filmes:index' %}">Nome</a>
                    <a class="dropdown-item" href="{% url 'filmes:index_data_antigo' %}">Data (Antigos)</a>
                    <a class="dropdown-item" href="{% url 'filmes:index_data_novo' %}">Data (Novos)</a>
                    <!-- <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Outras coisas...</a> -->
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Categorias
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for categoria in categorias %}

                    <a class="dropdown-item" href="{% url 'filmes:categoria' categoria.nome_cat %}" name="buscar">
                        {{ categoria.nome_cat }}
                    </a>

                    {% endfor %}
                </div>
            </li>
        </ul>

        <div class="collapse navbar-collapse justify-content-end" id="navbarResponsive" style="margin-right: 128px;">
            <ul class="navbar-nav dropdown">

                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Conta
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <span class="dropdown-item"><strong>Olá, <i>{{ request.user }}</i></strong></span>
                        <div class="linha"></div>
                        <a class="dropdown-item" href="{% url 'perfil:logout' %}">Sair</a>
                        <!-- <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Outras coisas...</a> -->
                    </div>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'perfil:login' %}">
                        <button class="btn btn-warning btn-sm"
                            style="width: 70px; font-size: 17px;"><strong>Login</strong></button>
                    </a>
                </li>
                {% endif %}
            </ul>


        </div>
    </div>
</nav>



<!-- <div class="dropdown-divider"></div>
<a class="dropdown-item" href="#"SAdicionar FOR</a> -->

templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1" style="color: black;">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" style="color: black;">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}" style="background-color: black; border: black;">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <li class="page-item">
            <a class="page-link" href="?page={{ num }}" style="color: black;">{{ num }}</a>
            </li>
            {% endif %}

            {% endfor %}

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="color: black;">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" style="color: black;">&raquo;</a>
            </li>
            {% endif %}
    </ul>
</div>
{% endif %}